[project]
name = "poc-monday-orange-csv-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "monday-code>=2.0.0",
    "pandas>=2.3.2",
    "pydantic-settings>=2.10.1",
]
